apiVersion: apps/v1
kind: Deployment
metadata:
  name: netboot
spec:
  replicas: 1
  selector:
    matchLabels:
      coop.ii: netboot
  template:
    metadata:
      labels:
        coop.ii: netboot
    spec:
      allowPrivilegeEscalation: true
      allowedCapabilities:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
      hostNetwork: true
      hostPorts:
      - max: 7472
        min: 7472
      privileged: true
    spec:
      containers:
      - name: netboot-pi
        image: "heyste/netboot-pi"
        ports:
        - containerPort: 8069
        - containerPort: 69
          hostPort: 69
          protocol: UDP
